### PR TITLE
Added a folder for assignments and the solution to the assignement

### PR DESCRIPTION
**Pull request by tannyakin**
Created a folder to store future assignments and also uploaded the solution to the python assignments

### CODE REVIEW

**Comment by tannyakin** [comment]
What do you think about the assignment solution?

**Comment by Samuel-IG16** [comment]
Yeah good idea creating a new folder for assignments.

**Comment by Samuel-IG16** [comment]
> What do you think about the assignment solution?

I just switched to your branch to test it and it worked without error. I would however ask that you use a more suitable file name (maybe number them in order) so we can tell the difference between the first, second and last assignment set. When you do you can open another request for review

**Comment by tannyakin** [comment]
Do you mean like separate each assignment into a separate file for each question and add them into a folder or the numbering of the question? I'm not quite clear on what you mean

**Comment by Samuel-IG16** [comment]
> Do you mean like separate each assignment into a separate file for each question and add them into a folder or the numbering of the question? I'm not quite clear on what you mean

I mean saving the file like this for example `0-assignment.py` is better so that subsequent assignments can be named `1-assignment`, `2-assignment` and so on....

**Pull request closed without merging**
